FROM dockerfile/java
ADD portlets-svc-1.0-SNAPSHOT.tgz /opt/portlets-svc
WORKDIR /opt/portlets-svc/portlets-svc-1.0-SNAPSHOT
RUN /opt/portlets-svc/portlets-svc-1.0-SNAPSHOT/bin/portlets-svc
EXPOSE 9000
